### ISSUE TITLE
Migrate the site's static generator to support better user experience

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#1587]
The Zowe doc site is built using Vuepress. With the content for the site growing in size and complexity, users need better user experience. 

### Why a new site generator is being considered

- Vuepress now has a limitation for the nav depth. It does not support nested sidebar thus some sections cannot be further organized. 
- We want to improve the current Vuepress site layout to be a standard three column layout supporting better navigation experience. 
- Many other functions are wanted but not available on the site now. For example, social functions like Share, Feedback, and more importantly the ability to generate a PDF file automatically. 
- Considering the growth of the community, multilingual support will be wanted for Zowe docs in the near future. 
 
Therefore, it's Explore there is better site generator choice. 

### Related issues

Some existing issues might be able to be addressed in the process. 

- #1376 Add 'share to social media' buttons on Zowe doc site 
- #1259 Doc Enhancement: Track and alert on last-updated topics 
- #730 Enhancement - Add Slack button, other UI improvements
- #558 Inconsistent Bold Headings in TOC
- #533 Enhancement - Dark Theme option
- #286 Allow Users to adjust the size of the TOC frame in the browser
- #653 Add Home Button/Icon to the Toolbar/nav menus
- #1672 Large Images are small in size and not properly readable

### Design requirements

- [x] More depth to sidebars (must support nested topics)
- [x] Three column layout (nav-topic-mini toc) 
- [x] Collapsible sidebar (can be changed into two column layout as per need)
- [x] Two themes (dark and light)
- [x] Algolia Search (AI-powered Search) 
- [x] Create a zoom-in effect for Doc Images 
- [x] Social module
   - [x] A "Share" button that allows users to share a topic to social platforms
   - [x] A "Discussion" button that opens Zowe Slack channels. It's in the footer section now as a resource. 
- [x] Feedback module
   - [x] Rate "Is this topic helpful" - thumbs up and thumbs down. Helpful or not helpful. When not helpful, ask users to create a Github issue. 
   - [x] "Open doc issue" for each topic that directs users to the doc site repo. 
      - [x] Better to associate the topic URL and some background information in the issue automatically.  
   - [x] "Edit this topic" link that directs users to the source file for each topic
- [x] Can print PDF (download the complete doc into PDF, not print a single topic) 
- [x] Support localization (also document how to do that for future reference)  
- [x] Support multi version of docs 
- [x] Support a home page
- [x] Google Analytics embedded - Ashley to share the account information 
- [x] Similar look and feel with zowe.org (includes footer) 
- [x] Supports Markdown syntax
- [x] Cannot change the doc URLs (to avoid broken links) 
- [x] Images are loading when you refresh the site, need to fix it.
- [x] Algolia: need to re-index the whole site and need support from Algolia team.
- [x] Optional: Support reading docs offline
- [x] Optional: Includes a "Estimated reading time: xx minutes " for each topic.

**Comment by nannanli** [comment]
Arijit Kundu is interested in working on this epic. He proposed a new site generator named **Docusaurus** (https://v2.docusaurus.io/docs/) and listed some of its advantages:
 - Three column layout, collapsible sidebar can be changed into two column layout as per need
 - Two themes are available (dark and light)
 - Algolia Search (AI-powered Search)
 - More depth to sidebars for better navigation experience
 - Supports a lot of plugins like plugins to generate site-maps (so that search engine crawlers can crawl your site more accurately
 - Plugins to create PWA-compliant documentation site with offline support to docs
 - Supports plugins to generate documentation into PDF
 - Comes with localization support of translating Docs into 70 languages
 - Ever growing community of Docusaurus, being maintained by Facebook Open Source Developers

We'll leverage this epic for discussion and feedback.

**Comment by covalentbond** [comment]
### Some more related issues:

- #532 Improve home page design (Home page can be customized accordingly as Docusaurus is buit on top of React
- #538 Enhance doc site UX
- #1374 Enhance Zowe doc SEO (Comes with official plugin to generate sitemaps)

**Comment by covalentbond** [comment]
The progress of this project can be checked on [zowe-docs-v2](https://github.com/zowe/docs-site/tree/zowe-docs-v2) branch.
