### ISSUE TITLE
Issue with docs.zowe.org/stable/troubleshoot/troubleshooting

### ISSUE THREAD

**Issue by Rinalusi44** [zowe/docs-site#3330]
## Additional context

```[tasklist]
### Tasks
- [ ] https://github.com/zowe/docs-site/pull/3334
- [ ] https://github.com/zowe/docs-site/pull/3332
- [ ] https://github.com/zowe/docs-site/pull/3333
- [ ] https://github.com/zowe/docs-site/pull/3319
- [ ] https://github.com/zowe/docs-site/issues/3328
- [ ] https://github.com/zowe/docs-site/pull/3324
- [ ] https://github.com/zowe/docs-site/pull/3331
- [ ] https://github.com/zowe/docs-site/pull/3329
```

**Comment by anaxceron** [comment]
@Rinalusi44  -- could you explain what the problem is in this issue? Need some context to understand what we should be addressing. Thanks!
