### ISSUE TITLE
Update hardcoded doc site URIs to docs.zowe.org

### ISSUE THREAD

**Issue by nannanli** [zowe/docs-site#650]
Message from John on the Slack channel: 

> We are working to get docs.zowe.org to resolve to https://zowe.github.io/docs-site. Both URLs will continue to work, but will get rewritten on the fly to docs.zowe.org ones. Not sure if you have any hardcoded URIs out there but if so you might want to update those once the transition is done. 

Need to check the doc site to respond to the impact. 
- if there are hardcoded URIs, need to change it to docs.zowe.org
- for other locations in the doc where https://zowe.github.io/docs-site is used, need tro check that the link does not break after the migration.

**Comment by jmertic** [comment]
docs.zowe.org is now live - will take a bit to propagate fully.

**Comment by nannanli** [comment]
### Goal
Update the doc site URL from `https://zowe.github.io/docs-site/` to `https://docs.zowe.org/`

### Tasks
**Step 1:** 
Communicate to teams on Slack that the URL change will happen soon. Better to state a date so people are prepared for the change. 

**Step 2:** 
Perform the following tasks on all versions to update the doc. Take `master` branch for example: 
- [ ]  Create a new branch.
- [ ]  Search in all files and replace the old URL with the new one. Needs considerations in some locations. Here are links we should check:
  * https://zowe.org/home/ menu bar on top and links on very bottom,
  * https://zowe.org/home/ "What's New" link in "Announcements" section,
  * https://zowe.org/home/ Documentation section at the bottom,
  * https://zowe.org/download/ documentation links,
  * https://zowe.org/faq/ Resources section at the bottom,
  * https://zowe.org/contribute/ Onboarding GitHub URL,
  * https://projectgiza.org/Downloads/post_download.???.html Documentation links.
  * Verify Google Analytics tracking code.
- [ ]  Test and fix gh-pages 404 and redirect handling
- [ ] Create pull request on Algolia search configurations at https://github.com/algolia/docsearch-configs/blob/master/configs/zowe.json.
- [ ] Does Jenkins need to be updated? @jackjia-ibm 
   * Jenkins of building gh-pages,
   * Jenkins of building PDF file.

**Step 3:** 
After the change is made, 
- [ ] need to run link checker and fix broken links. 
- [ ] need Cathy (Chen Ting) to update the sitemap for SEO in all versions.
- [ ] need to do a full test of all versions to ensure that everything works

**Step 4:** 
After the test passes on all versions， 
- [ ] inform John @jmertic to change the URL in DNS. Need to schedule a time for this so we could revert as needed in case the site breaks unexpectedly. 

The steps might take 1-2 days. 

Although the old URL will be automatically redirected to the new one, there are still some work that could be done.
- Notify teams to modify other pages, like repository READMEs of zowe-cli, db2 plugin, cics plugin, vsc plugin, sample plugin, etc.
- Do we have other websites, or maybe mailing list information which link to https://zowe.github.io/docs-site, or rely on https://github.com/zowe/docs-site repository? If yes, we could update the URL to the new one. 

Please add to this list any locations that might have been missed. Thanks!

**Comment by jackjia-ibm** [comment]
@nannanli there are few changes needed on build/test:
- the base url for generating latest docs
- archived versions need to be updated to generating with new relative path
- link checker command needs to be updated with the new relative path
- pdf generating should be ok, but i will validate it.

I can create PRs for those changes, will be several for both master and archived versions.

**Comment by nannanli** [comment]
@jackjia-ibm Thanks Jack!

**Comment by jackjia-ibm** [comment]
@nannanli @BrandonJenkins14 if you like, we can sync the work of migrating `latest` to `stable` with this issue. That work has similar efforts of updating all archived versions.

**Comment by nannanli** [comment]
@jackjia-ibm I agree, this is a good opportunity to make all the changes and do a full test. I'm wondering what effort will be needed. Anything that I need to take care? Thanks!

**Comment by jackjia-ibm** [comment]
All PRs are merged.
